[advisories]
# Binary Protocol Misinterpretation caused by Truncating or Overflowing Casts
# actix_web default limit for text extractor is 256kb, vulnerable if > 4GiB
# TODO(aalhendi): eventually update whenever sqlx updates
ignore = ["RUSTSEC-2024-0363"]
